config/routes.rb
Virtuio::Application.routes.draw do
  
  devise_for :users
  resources :invoices do
    member do
      get 'send_to_client' => 'invoices#send_to_client'
    end
  end

  resources :clients
  resources :charges

  get "sessions/new"
  resources :users
  resources :sessions

  root :to => "home#index"
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base

	belongs_to :client
	belongs_to :user


end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    @invoices = Invoice.where(:user_id => current_user.id)
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
    @amount = @invoice.amount
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
    @user = current_user    
    @clients = @user.clients
  end

  # GET /invoices/1/edit
  def edit
    @user = current_user    
    @clients = @user.clients
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @user = current_user    
    @clients = @user.clients
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render action: 'show', status: :created, location: @invoice }
      else
        format.html { render action: 'new' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url }
      format.json { head :no_content }
    end
  end

  def send_to_client
    @user = current_user
    @invoice = Invoice.find_by_id(params[:invoice_id])
    @client = @invoice.client
    UserMailer.invoice_email(@user, @invoice).deliver
    redirect_to @invoice, notice: "Invoice successfully sent to #{@client.name}. A copy was also sent to your email address at #{@user.email}."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:client_id, :user_id, :description, :amount, :date_paid, :date_due)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h2>
      <ul>
      <% @invoice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.hidden_field :user_id, :value => current_user.id  %>
  <div class="field">
      <select name="invoice[client_id]">
        <% @clients.sort{ |a,b| a.name <=> b.name}.each do |client|%>
          <% if client && (client == @invoice.client) %>
            <option value=<%= client.id %> selected="selected"><%= client.name %></option> 
          <% else %>
            <option value=<%= client.id %>><%= client.name %></option> 
          <% end %>
        <% end %>
        <% unless @invoice.client %>
          <option selected="selected">Select client</option>
        <% end %>
     </select>
  </div>
  <!-- <div class="field"> -->
  <%#= f.select(:client_id, options_for_select(@clients.collect {|client| [ client.name, client.id ]}, "Choose client" )) %>
  <!-- </div> -->
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :date_paid %><br>
    <%= f.text_field :date_paid %>
  </div>
  <div class="field">
    <%= f.label :date_due %><br>
    <%= f.text_field :date_due %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<h1>Invoices</h1>

<table>
  <thead>
    <tr>
      <th>Client</th>
      <th>Amount</th>
      <th>Date due</th>
      <th>Date paid</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
      <% @invoices.each do |invoice| %>
        <tr>
          <td><%= invoice.client.name %></td>
          <td><%= invoice.amount %></td>
          <td><%= invoice.date_due %></td>
          <td><%= invoice.date_paid %></td>
          <td><%= invoice.description %></td>
          <td><%= link_to 'Show', invoice %></td>
          <td><%= link_to 'Edit', edit_invoice_path(invoice) %></td>
          <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Invoice', new_invoice_path %>

app/views/invoices/new.html.erb
<h1>New invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path %>

app/views/invoices/show.html.erb
<p>
  <strong>Client:</strong>
  <%= @invoice.client.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @invoice.description %>
</p>

<p>
  <strong>Amount:</strong>
  <%= number_to_currency(@invoice.amount) %>
</p>

<p>
  <strong>Date due:</strong>
  <%= @invoice.date_due.to_time.strftime("%b %e, %Y at %I:%M %P") %>
</p>


<p>[If client, show link to submit payment]</p>
<% if @invoice.date_paid.empty? %>
  <%= render partial: "charges/form", locals: {invoice: @invoice} %>
<% else %>
  <p>
    <strong>Date paid:</strong>
    <%= @invoice.date_paid.to_time.strftime("%b %e, %Y at %I:%M %P") %>
  </p>
<% end %>

<p>[if admin user, show link to send invoice to client]</p>
<p>"Click Here" to email this invoice to <%= @invoice.client.name %></p>
<p><%= link_to "Send invoice", send_to_client_invoice_path(:invoice_id => @invoice.id) %></p>

<%= link_to 'Edit', edit_invoice_path(@invoice) %> |
<%= link_to 'Back', invoices_path %>