config/routes.rb
Virtuio::Application.routes.draw do
  
  devise_for :users
  resources :invoices do
    member do
      get 'send_to_client' => 'invoices#send_to_client'
    end
  end

  resources :clients
  resources :charges

  get "sessions/new"
  resources :users
  resources :sessions

  root :to => "home#index"
  
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Virtuio</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag "/favicon.ico" %>
</head>
<body class ="container-home">
<div id="user_header">
  <% if current_user && current_user.invoices %>
    <%= link_to 'Invoices', invoices_path %> | <%= link_to 'Clients', user_path(current_user) %> | 
  <% end %>
  <% if current_user %>
    Logged in as <%= link_to current_user.name, user_path(current_user) %> | 
    <%= link_to "Log out", logout_path %>
  <% else %>
  	<%= link_to "Sign up", signup_path %> or
  	<%= link_to "Login", login_path %>
  <% end %>
</div>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>